-- MySQL Script generated by MySQL Workbench
-- Sun Sep 25 22:32:45 2016
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema nanotwitter_dev
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema nanotwitter_dev
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `nanotwitter_dev` DEFAULT CHARACTER SET utf8 ;
USE `nanotwitter_dev` ;

-- -----------------------------------------------------
-- Table `nanotwitter_dev`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `nanotwitter_dev`.`users` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(20) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `passwd` VARCHAR(20) NOT NULL,
  `create_time` DATETIME NOT NULL,
  `gender` ENUM('male','female','unknown') NOT NULL DEFAULT 'unknown',
  `birthday` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `nanotwitter_dev`.`tweets`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `nanotwitter_dev`.`tweets` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `user_id` INT(11) NOT NULL,
  `likes` INT(11) NOT NULL DEFAULT '0',
  `content` TEXT NOT NULL,
  `create_time` DATETIME NOT NULL,
  `comments` INT(11) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  INDEX `user_id_idx` (`user_id` ASC),
  CONSTRAINT `user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `nanotwitter_dev`.`users` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `nanotwitter_dev`.`comments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `nanotwitter_dev`.`comments` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `tweet_id` INT(11) NOT NULL,
  `user_id` INT(11) NOT NULL,
  `content` TEXT NOT NULL,
  `create_time` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `tweet_id_in_comments_idx` (`tweet_id` ASC),
  INDEX `user_id_in_comments_idx` (`user_id` ASC),
  CONSTRAINT `tweet_id_in_comments`
    FOREIGN KEY (`tweet_id`)
    REFERENCES `nanotwitter_dev`.`tweets` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `user_id_in_comments`
    FOREIGN KEY (`user_id`)
    REFERENCES `nanotwitter_dev`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `nanotwitter_dev`.`follows`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `nanotwitter_dev`.`follows` (
  `follower_id` INT(11) NOT NULL,
  `followed_id` INT(11) NOT NULL,
  `create_time` DATETIME NOT NULL,
  PRIMARY KEY (`follower_id`, `followed_id`),
  INDEX `followed_id_idx` (`followed_id` ASC),
  INDEX `follower_id_idx` (`follower_id` ASC),
  CONSTRAINT `followed_id`
    FOREIGN KEY (`followed_id`)
    REFERENCES `nanotwitter_dev`.`users` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `follower_id`
    FOREIGN KEY (`follower_id`)
    REFERENCES `nanotwitter_dev`.`users` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `nanotwitter_dev`.`likes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `nanotwitter_dev`.`likes` (
  `user_id` INT(11) NOT NULL,
  `tweet_id` INT(11) NOT NULL,
  PRIMARY KEY (`user_id`, `tweet_id`),
  INDEX `tweet_id_in_likes_idx` (`tweet_id` ASC),
  INDEX `user_id_in_likes_idx` (`user_id` ASC),
  CONSTRAINT `tweet_id_in_likes`
    FOREIGN KEY (`tweet_id`)
    REFERENCES `nanotwitter_dev`.`tweets` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `user_id_in_likes`
    FOREIGN KEY (`user_id`)
    REFERENCES `nanotwitter_dev`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `nanotwitter_dev`.`notifications`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `nanotwitter_dev`.`notifications` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `target_user_id` INT(11) NOT NULL,
  `tweet_id` INT(11) NOT NULL,
  `status` ENUM('read','unread') NOT NULL DEFAULT 'unread',
  `type` ENUM('mention','reply') NOT NULL,
  `action_user_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `target_user_id_idx` (`target_user_id` ASC),
  INDEX `tweet_id_idx` (`tweet_id` ASC),
  INDEX `action_user_id_idx` (`action_user_id` ASC),
  CONSTRAINT `action_user_id`
    FOREIGN KEY (`action_user_id`)
    REFERENCES `nanotwitter_dev`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `target_user_id`
    FOREIGN KEY (`target_user_id`)
    REFERENCES `nanotwitter_dev`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `tweet_id_in_notifications`
    FOREIGN KEY (`tweet_id`)
    REFERENCES `nanotwitter_dev`.`tweets` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `nanotwitter_dev`.`tags`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `nanotwitter_dev`.`tags` (
  `tag_name` VARCHAR(20) NOT NULL,
  `tweet_id` INT(11) NOT NULL,
  PRIMARY KEY (`tag_name`, `tweet_id`),
  INDEX `tweet_id_idx` (`tweet_id` ASC),
  INDEX `tag_name_idx` (`tag_name` ASC),
  CONSTRAINT `tweet_id_in_tags`
    FOREIGN KEY (`tweet_id`)
    REFERENCES `nanotwitter_dev`.`tweets` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
