## This file is for database creation

development:
  adapter: postgresql
  encoding: utf8
  database: twitter_dev
  pool: 10
  username: <%= ENV["PG_USER"] %>
  password: <%= ENV["PG_PASS"] %>
  host: localhost

